name: dox_sample
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dox_core: ^0.0.12

dev_dependencies:
  dox_builder: ^0.0.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
 
assets:
  - .env