name: dox_sample
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  postgres: ^2.6.1
  sql_query_builder: ^1.1.0
  json_annotation: ^4.8.0
  path: ^1.8.3
  dox_core: ^0.0.1

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
 
assets:
  - .env