name: dox_sample
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dox_core: 2.0.0-alpha.1
  postgres_pool: ^2.1.6
  dox_query_builder: ^1.1.15
  dox_migration: ^1.0.4

dev_dependencies:
  dox_builder: ^1.0.3
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.0.0

assets:
  - .env