name: dox_sample
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dox_core: ^2.0.0
  dox_query_builder: ^2.0.0
  dox_migration: ^2.0.0
  postgres: ^3.0.5

dev_dependencies:
  dox_builder: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  http: ^1.1.2
